#!/bin/bash
# embed-cover-art.sh — Render a still cover image and attach it to MP4 as cover art
#
# Usage: embed-cover-art.sh <entry-file> <composition-id> <output-mp4>
#
# Notes:
# - Cover source: composition's last frame (durationInFrames - 1) parsed from Root.tsx
# - Embedding method: MP4 attached picture (ffmpeg `attached_pic`)
# - Failure policy: this script never fails the overall pipeline; it falls back gracefully.

set -uo pipefail

ENTRY_FILE="${1:?Usage: embed-cover-art.sh <entry-file> <composition-id> <output-mp4>}"
COMPOSITION_ID="${2:?Missing composition ID}"
OUTPUT_MP4="${3:?Missing output MP4 path}"

if [ ! -f "${OUTPUT_MP4}" ] || [ ! -s "${OUTPUT_MP4}" ]; then
  echo "Warning: embed-cover-art: output MP4 missing/empty (${OUTPUT_MP4})" >&2
  exit 0
fi

if ! command -v ffmpeg &>/dev/null; then
  echo "Warning: embed-cover-art: ffmpeg not found, skipping cover embedding" >&2
  exit 0
fi

if [ ! -f "${ENTRY_FILE}" ]; then
  echo "Warning: embed-cover-art: entry file not found (${ENTRY_FILE}), skipping" >&2
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RENDER_STILL_SH="${SCRIPT_DIR}/render-still.sh"
if [ ! -x "${RENDER_STILL_SH}" ]; then
  echo "Warning: embed-cover-art: render-still.sh not found/executable, skipping" >&2
  exit 0
fi

ROOT_TSX="$(cd "$(dirname "${ENTRY_FILE}")" && pwd)/Root.tsx"
if [ ! -f "${ROOT_TSX}" ]; then
  echo "Warning: embed-cover-art: Root.tsx not found (${ROOT_TSX}), using frame 0" >&2
  LAST_FRAME=0
else
  DURATION_IN_FRAMES="$(
    node -e "
      const fs = require('fs');
      const path = process.argv[1];
      const compId = process.argv[2];
      const content = fs.readFileSync(path, 'utf8');

      function firstMatch(re) {
        const m = content.match(re);
        return m && m[1] ? m[1] : null;
      }

      // Prefer durationInFrames from the Composition block matching `id=\"${compId}\"`.
      const blockRe = new RegExp(
        'id\\\\s*=\\\\s*[\"\\\']' + compId.replace(/[.*+?^${}()|[\\\\]\\\\]/g, '\\\\$&') + '[\"\\\'][\\\\s\\\\S]*?durationInFrames\\\\s*=\\\\s*\\\\{?\\\\s*([0-9]+)\\\\s*\\\\}?'
      );
      const d1 = firstMatch(blockRe);
      const d2 = firstMatch(/durationInFrames\\s*=\\s*\\{?\\s*([0-9]+)\\s*\\}?/);

      const val = d1 || d2;
      if (!val) process.exit(0);
      process.stdout.write(String(val));
    " "${ROOT_TSX}" "${COMPOSITION_ID}" 2>/dev/null
  )"

  if [ -z "${DURATION_IN_FRAMES}" ]; then
    echo "Warning: embed-cover-art: couldn't parse durationInFrames, using frame 0" >&2
    LAST_FRAME=0
  else
    LAST_FRAME=$((DURATION_IN_FRAMES - 1))
    if [ "${LAST_FRAME}" -lt 0 ]; then
      LAST_FRAME=0
    fi
  fi
fi

COVER_PNG="/tmp/remotion-cover-$$.png"
COVER_JPG="/tmp/remotion-cover-$$.jpg"
TMP_OUT="${OUTPUT_MP4}.cover_tmp.$$"

cleanup() {
  rm -f "${COVER_PNG}" "${COVER_JPG}" "${TMP_OUT}" 2>/dev/null || true
}
trap cleanup EXIT

echo "Embedding MP4 cover art: frame ${LAST_FRAME} (${COMPOSITION_ID})" >&2

if ! bash "${RENDER_STILL_SH}" "${ENTRY_FILE}" "${COMPOSITION_ID}" "${LAST_FRAME}" "${COVER_PNG}"; then
  echo "Warning: embed-cover-art: still render failed, skipping cover embedding" >&2
  exit 0
fi

if [ ! -f "${COVER_PNG}" ] || [ ! -s "${COVER_PNG}" ]; then
  echo "Warning: embed-cover-art: cover PNG missing/empty, skipping" >&2
  exit 0
fi

# Convert to a small JPEG for efficient attachment.
if ! ffmpeg -y -hide_banner -loglevel error -i "${COVER_PNG}" \
  -vf "scale='min(480,iw)':-1:flags=lanczos" -q:v 2 "${COVER_JPG}"; then
  echo "Warning: embed-cover-art: JPEG conversion failed, skipping" >&2
  exit 0
fi

if [ ! -f "${COVER_JPG}" ] || [ ! -s "${COVER_JPG}" ]; then
  echo "Warning: embed-cover-art: cover JPG missing/empty, skipping" >&2
  exit 0
fi

# Re-mux the original MP4, attaching the JPEG as cover art.
# -map 0: all streams from the original MP4
# -map 1:v:0: the cover image stream
if ! ffmpeg -y -hide_banner -loglevel error \
  -i "${OUTPUT_MP4}" -i "${COVER_JPG}" \
  -map 0 -map 1:v:0 \
  -c copy \
  -c:v:1 mjpeg \
  -disposition:v:1 attached_pic \
  -metadata:s:v:1 title="Cover" \
  -metadata:s:v:1 comment="Generated by Sabai Remotion" \
  "${TMP_OUT}"; then
  echo "Warning: embed-cover-art: remux failed, keeping original MP4 without cover" >&2
  exit 0
fi

if [ ! -f "${TMP_OUT}" ] || [ ! -s "${TMP_OUT}" ]; then
  echo "Warning: embed-cover-art: remux output missing/empty, keeping original MP4 without cover" >&2
  exit 0
fi

mv "${TMP_OUT}" "${OUTPUT_MP4}"
echo "MP4 cover art embedded successfully: ${OUTPUT_MP4}" >&2

